/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2022-08-18 02:00:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t#condition {\r\n");
      out.write("\t\toverflow:hidden;\r\n");
      out.write("\t\tmargin-top: 50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#condition form {\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#condition #right {\r\n");
      out.write("\t\tfloat:right;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#condition button, .buttons button {\r\n");
      out.write("\t\tpadding:5px 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#products {\r\n");
      out.write("\t\toverflow:hidden;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#products .box {\r\n");
      out.write("\t\twidth: 200px;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tmargin: 10px;\r\n");
      out.write("\t\tpadding: 8px;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#products .box .name { \r\n");
      out.write("\t\twidth: 200px;\r\n");
      out.write("\t\tfont-size: 15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#products .box img {\r\n");
      out.write("\t\tborder:2px solid green; \r\n");
      out.write("\t\tborder-radius : 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#new, #best {\r\n");
      out.write("\t\toverflow:hidden;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#new .box, #best .box {\r\n");
      out.write("\t\twidth: 150px;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tmargin-left: 35px;\r\n");
      out.write("\t\tfont-size: 13px;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<h1>최신상품</h1>\r\n");
      out.write("<div id = \"new\"></div>\r\n");
      out.write("<script id=\"ntemp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t{{#each array}}\r\n");
      out.write("\t<div class = \"box\" style = \"text-align: center\" onclick = \"location.href = '/pro/info?prod_id={{prod_id}}'\">\r\n");
      out.write("\t\t<img src = \"/image/shop/{{image}}\" width = 150>\r\n");
      out.write("\t\t<div class = \"name ellipsis\">{{prod_name}}</div>\r\n");
      out.write("\t\t<div class = \"price\">{{fprice}}</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t{{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<h1 style = \"margin-top: 50px;\">베스트상품</h1>\r\n");
      out.write("<div id = \"best\"></div>\r\n");
      out.write("<script id=\"ntemp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t{{#each array}}\r\n");
      out.write("\t<div class = \"box\" style = \"text-align: center\" onclick = \"location.href = '/pro/info?prod_id={{prod_id}}'\">\r\n");
      out.write("\t\t<img src = \"/image/shop/{{image}}\" width = 150>\r\n");
      out.write("\t\t<div class = \"name ellipsis\">{{prod_name}}</div>\r\n");
      out.write("\t\t<div class = \"price\">{{fprice}}</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t{{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<h2 style = \"margin-top: 50px; border-bottom: 5px solid green; width: 200px\" >빠른 상품 검색</h2>\r\n");
      out.write("<div  id = \"condition\">\r\n");
      out.write("\t<form name = \"frm\">\r\n");
      out.write("\t\t<select id = \"key\">\r\n");
      out.write("\t\t\t<option value = \"prod_name\">상품명</option>\r\n");
      out.write("\t\t\t<option value = \"company\">제조사</option>\r\n");
      out.write("\t\t\t<option value = \"mall_name\">판매처</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<input type = \"text\" id = \"word\" placeholder = \"검색어\">\r\n");
      out.write("\t\t<button>검색</button>\r\n");
      out.write("\t\t검색수 : <span id = \"count\"></span>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div id = \"right\">\r\n");
      out.write("\t\t<select id = \"order\">\r\n");
      out.write("\t\t\t<option value = \"price1\">상품가격</option>\r\n");
      out.write("\t\t\t<option value = \"prod_name\">상품명</option>\t\t\t\r\n");
      out.write("\t\t\t<option value = \"prod_id\">상품코드</option>\t\t\t\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<select id = \"desc\">\r\n");
      out.write("\t\t\t<option value = \"asc\">오름차순</option>\r\n");
      out.write("\t\t\t<option value = \"desc\">내림차순</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id = \"products\"></div>\r\n");
      out.write("<script id=\"ptemp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t{{#each array}}\r\n");
      out.write("\t<div class = \"box\" style = \"text-align: center\" onclick = \"location.href = '/pro/info?prod_id={{prod_id}}'\">\r\n");
      out.write("\t\t<img src = \"/image/shop/{{image}}\" width = 200>\r\n");
      out.write("\t\t<div class =\"id\"><b>{{prod_id}}</b><span class = \"del\" style = \"color: red; font-weight: bold;\"> {{status del}}</span></div>\r\n");
      out.write("\t\t<div class = \"name ellipsis\">{{prod_name}}</div>\r\n");
      out.write("\t\t<div class = \"price\">{{fprice}}</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t{{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tHandlebars.registerHelper(\"status\", function(del) {\r\n");
      out.write("\t\tif(del == '1') {\r\n");
      out.write("\t\t\treturn \"판매중지\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class = \"buttons\" style = \"text-align: center; margin-top: 20px;\">\r\n");
      out.write("\t<button id = \"prev\">이전</button>\r\n");
      out.write("\t<span id = \"page\">1/10</span>\r\n");
      out.write("\t<button id = \"next\">다음</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar page = 1;\r\n");
      out.write("\tgetProducts();\r\n");
      out.write("\tgetNews();\r\n");
      out.write("\tgetBest();\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#next\").on(\"click\", function() {\r\n");
      out.write("\t\tpage++;\r\n");
      out.write("\t\tgetProducts();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#prev\").on(\"click\", function() {\r\n");
      out.write("\t\tpage--;\r\n");
      out.write("\t\tgetProducts();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(frm).on(\"submit\", function(e) {\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\tpage = 1;\r\n");
      out.write("\t\tgetProducts();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#per, #order, #desc\").on(\"change\", function() {\r\n");
      out.write("\t\tpage = 1;\r\n");
      out.write("\t\tgetProducts();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getProducts() {\r\n");
      out.write("\t\tvar key = $(\"#key\").val();\r\n");
      out.write("\t\tvar word = $(\"#word\").val();\r\n");
      out.write("\t\tvar per = 8;\r\n");
      out.write("\t\tvar order = $(\"#order\").val();\r\n");
      out.write("\t\tvar desc = $(\"#desc\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax ({\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\turl : \"/pro/list.json\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tdata : {key : key, word : word, per : per, order : order, desc : desc, page : page},\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tvar temp = Handlebars.compile($(\"#ptemp\").html());\r\n");
      out.write("\t\t\t\t$(\"#products\").html(temp(data));\r\n");
      out.write("\t\t\t\t$(\"#count\").html(data.total);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(data.total == 0) {\r\n");
      out.write("\t\t\t\t\t$(\"#products\").append(\"<div class = 'none' style = 'text-align: center; color: red; padding : 300px 0px;'> <h3>검색된 자료가 없습니다! </h3> </div>\");\r\n");
      out.write("\t\t\t\t\t$(\".buttons\").hide();\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t$(\"#page\").html(page + \"/\" + data.last);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(page == 1) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#prev\").attr(\"disabled\", true);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t\t$(\"#prev\").attr(\"disabled\", false);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(page == data.last) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#next\").attr(\"disabled\", true);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t\t$(\"#next\").attr(\"disabled\", false);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\".buttons\").show();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getNews() {\r\n");
      out.write("\t\t$.ajax ({\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\turl : \"/pro/list.json\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tdata : {key : \"prod_id\", word : \"\", per : 5, order : \"prod_id\", desc : \"desc\", page : 1},\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tvar temp = Handlebars.compile($(\"#ntemp\").html());\r\n");
      out.write("\t\t\t\t$(\"#new\").html(temp(data));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getBest() {\r\n");
      out.write("\t\t$.ajax ({\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\turl : \"/pro/list.json\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tdata : {key : \"prod_id\", word : \"\", per : 5, order : \"price1\", desc : \"asc\", page : 1},\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tvar temp = Handlebars.compile($(\"#ntemp\").html());\r\n");
      out.write("\t\t\t\t$(\"#best\").html(temp(data));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
