/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2022-08-16 01:16:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.stu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<h1>학생 등록</h1>\r\n");
      out.write("<form name = \"frm\" method = \"post\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>학생번호</td>\r\n");
      out.write("\t\t\t<td><input type = \"text\" name = \"scode\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>학생이름</td>\r\n");
      out.write("\t\t\t<td><input type = \"text\" name = \"sname\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>학생학과</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<select name = \"dept\">\r\n");
      out.write("\t\t\t\t\t<option value = \"전산\">컴퓨터공학과</option>\r\n");
      out.write("\t\t\t\t\t<option value = \"전자\">전자공학과</option>\r\n");
      out.write("\t\t\t\t\t<option value = \"건축\">건축공학과</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>학생학년</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type = \"radio\" name = \"year\" value = \"1\">1학년&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<input type = \"radio\" name = \"year\" value = \"2\" checked>2학년&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<input type = \"radio\" name = \"year\" value = \"3\">3학년&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<input type = \"radio\" name = \"year\" value = \"4\">4학년&nbsp;&nbsp;\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>생년월일</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type = \"date\" name = \"birthday\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${birthday}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\t\t\t\t\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>지도교수</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<select name = \"advisor\" id = \"advisor\" ></select>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div class = \"buttons\">\r\n");
      out.write("\t\t<button type = \"submit\">학생등록</button>\r\n");
      out.write("\t\t<button type = \"reset\">등록취소</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script id = \"temp\" type = \"text/x-handlebars-template\">\r\n");
      out.write("\t{{#each array}}\r\n");
      out.write("\t\t<option value = \"{{pcode}}\">{{pname}}({{dept}} : {{pcode}})</option>\r\n");
      out.write("\t{{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tchangeDept();\r\n");
      out.write("\t\r\n");
      out.write("\tfunction changeDept() {\r\n");
      out.write("\t\tvar dept = $(frm.dept).val();\r\n");
      out.write("\t\t$.ajax ({\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\turl : \"/pro/list.json\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tdata : {key : \"dept\", word : dept, per : 100, order : \"pname\", desc : \"\", page : 1},\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tvar temp = Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("\t\t\t\t$(\"#advisor\").html(temp(data));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(frm.dept).on(\"change\", function() {\r\n");
      out.write("\t\tchangeDept();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("   \t$(frm).on(\"submit\",function(e){\r\n");
      out.write("      e.preventDefault();\r\n");
      out.write("      var sname=$(frm.sname).val();\r\n");
      out.write("      \r\n");
      out.write("      if(sname==\"\") {\r\n");
      out.write("         alert(\"학생이름을 입력하세요.\");\r\n");
      out.write("         $(frm.pname).focus();\r\n");
      out.write("         return;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      if(!confirm(\"새로운 학생을 등록하시겠습니까?\")) {\r\n");
      out.write("    \t  \treturn;\r\n");
      out.write("      } \r\n");
      out.write("      else {\r\n");
      out.write("    \t   \tfrm.submit(); \t  \r\n");
      out.write("      }\r\n");
      out.write("   \t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
